commercelayer/mfe-checkout

- .github/workflows/release.yml
- .vscode/launch.json
- package.json
- pages/api/settings.ts
- fix: Node engine version
- fix: Development by localhost
- chore: Add semantic-release and update Github Actions
> fix: Localhost development

- README.md
This PR updates some links to the documentation that has changed.
> update links to docs

- components/composite/StepComplete/index.tsx
- components/composite/StepPayment/PaymentDetails/index.tsx
- components/composite/StepPayment/index.tsx
- components/composite/StepShipping/index.tsx
- package.json
- public/static/locales/en/common.json
- public/static/locales/it/common.json
- yarn.lock
> Display stock transfer when shipping from primary

- components/composite/StepComplete/SupportMessage/index.tsx
- components/composite/StepComplete/SupportMessage/styled.tsx
- components/composite/StepComplete/index.tsx
- components/composite/StepComplete/styled.tsx
Adjust padding on thankyou page
#247
> Adjust padding on message and btn on thankyou page

- components/composite/StepPayment/CheckoutPayment.tsx
- components/composite/StepPayment/styled.tsx
- package.json
- specs/e2e/payments.spec.ts
- specs/e2e/shipments.spec.ts
- yarn.lock
- fix: use group selector on payment cards
- test: add check for payment recap on thank you page reload
- fix: thank you page with data on page reload
> Fix thank you page data on page reload

- README.md
- Reworked _Getting started_ steps list to add `NEXT_PUBLIC_SLUG` env var.
- Added _Features_ section
> docs: added feature details

- components/data/AppProvider/index.tsx
- components/data/GTMProvider/index.tsx
- specs/e2e/GTM.spec.ts
- specs/e2e/customer-addresses-with-wallet.spec.ts
- specs/e2e/shipments-multiple.spec.ts
- resolves #283 
- resolves #282
> Fix customer addresses and add bundles to GTM dataLayer

- next.config.js
- package.json
- pnpm-lock.yaml
This PR will use a build id based on the commit hash when building and exporting the project
- resolves #300
> Use consistent, git-based build id on `build` and `export`

- components/composite/OrderSummary/ReturnToCart/index.tsx
This PR will fix the return to cart link after the checkout url has been aligned to all other micro frontend applications.
- resolves #317
> Fix return to cart link

- .circleci/config.yml
- playwright.config.ci.ts
- playwright.config.ts
- specs/fixtures/CheckoutPage.ts
This PR will rerun failed tests only
-resolves #329
> Rerun failed tests on CircleCI

- specs/fixtures/CheckoutPage.ts
Closes #347 
All test suite is green now.
Run on CircleCI
> Adjust test suite for klarna via Adyen and PayPal

- README.md
Closes #350 
This PR will add a not to the README related to external shipping cost.
Nothing to test
> Add external shipping cost note

- .do/deploy.template.yaml
- components/composite/Checkout/index.tsx
- components/composite/CheckoutSkeleton/index.tsx
- components/composite/StepPayment/styled.tsx
- components/composite/StepShipping/index.tsx
- components/composite/StepShipping/styled.tsx
- components/ui/Accordion/index.tsx
- components/ui/Card/index.tsx
- package.json
- pnpm-lock.yaml
- specs/e2e/payments-adyen.spec.ts
> Layout revamping

- specs/fixtures/CheckoutPage.ts
Closes #373 
I've updated fixtures to match the new German text for Klarna e2e test.
> Update selector for Klarna payment terms checkbox (german)

- package.json
- pnpm-lock.yaml
- specs/e2e/GTM.spec.ts
> Update react components

- package.json
- pnpm-lock.yaml
> Avoid check on country code lock for digital orders

- .eslintrc.json
- README.md
- components/composite/StepPayment/index.tsx
- components/data/AppProvider/utils.ts
- components/data/GTMProvider/index.tsx
Closes #392 closes #391 closes #386 
This PR will add a link to the security page of the corporate website and remove useless `async` statements. We also added a new eslint rule to force the check, enabling `require-await` rule.
> Remove useless `async` and add a link to the security page

- components/composite/Checkout/index.tsx
- components/data/GTMProvider/index.tsx
- specs/e2e/GTM.spec.ts
> Skip `begin_checkout` event when completing payment or reload page on `placed` orders

- components/data/GlobalStylesProvider/index.tsx
- components/ui/Accordion/index.tsx
- components/ui/form/Input.tsx
Closes #402 
This PR will darken primary light color and make animations quicker.
All inputs will have a `shadow-sm` class as the customer email input.
> Adjust duration and make primary light color darker

- components/data/AppProvider/utils.ts
> Improve check for `subscription_created_at` attribute

- specs/fixtures/CheckoutPage.ts
> Adjust klarna test

- README.md
- components/data/i18n/index.ts
- public/static/locales/es/common.json
> Add Spanish support and translations

- README.md
- components/data/i18n/index.ts
- public/static/locales/fr/common.json
Closes #438 
This PR will add support for French translations.
> 🌐 Add French translations

- README.md
- components/data/i18n/index.ts
- public/static/locales/fr/common.json
> Add french translations

- README.md
> docs: add order subscriptions support

- README.md
- components/composite/StepCustomer/AddressInputGroup/index.tsx
- components/composite/StepCustomer/BillingAddressFormNew/index.tsx
- components/composite/StepCustomer/ShippingAddressFormNew/index.tsx
- package.json
- pnpm-lock.yaml
- specs/e2e/guest-addresses.spec.ts
- specs/e2e/payments-adyen.spec.ts
- specs/e2e/shipments-errors.spec.ts
- specs/e2e/thank-you-page.spec.ts
- specs/fixtures/CheckoutPage.ts
- specs/fixtures/tokenizedPage.ts
> Override countries and states and preselect a default country

- next.config.js
> Avoid pruning adyen supported languages

- specs/e2e/entrypoint.spec.ts
- utils/getSettings.ts
> Avoid infinite loop when token is expired

- package.json
- pnpm-lock.yaml
- specs/e2e/payments-stripe-errors.spec.ts
- specs/fixtures/CheckoutPage.ts
> Address vulnerability on dependencies

- README.md
> Update need help section

- components/composite/StepPayment/PaymentContainer/index.tsx
- components/composite/StepPayment/styled.tsx
> Add new styles for adyen dropin

- components/data/AppProvider/utils.ts
- package.json
- pnpm-lock.yaml
- specs/fixtures/CheckoutPage.ts
- utils/getSettings.ts
Closes #510
Add support to Stripe Connected Account.
> Add support to Stripe Connected Account

- specs/e2e/thank-you-page.spec.ts
- utils/getSettings.ts
> Add organization slug support on config URLs

- biome.json
- components/composite/OrderSummary/ReturnToCart/index.tsx
- components/composite/StepCustomer/AddressInputGroup/index.tsx
- components/composite/StepCustomer/index.tsx
- components/composite/StepPayment/index.tsx
- components/composite/StepShipping/Errors/NoShippingMethods.tsx
- components/composite/StepShipping/Errors/OutOfStock.tsx
- components/composite/StepShipping/index.tsx
- components/data/GTMProvider/index.tsx
- components/hooks/useActiveStep.ts
Closes #523 
This PR includes the following biome rule and all the needed changes:
```
"correctness": {
"useHookAtTopLevel": "error"
}
```
> Enforce rule of hooks and avoid calling hooks conditionally

- package.json
- pnpm-lock.yaml
- specs/fixtures/CheckoutPage.ts
Closes #527 
This PR will avoid error when using Apple Pay on slow network.
> Check order status on Stripe dropin `onChange` event to avoid delay on Apple Pay modal

- .circleci/config.yml
- playwright.config.ci.ts
- specs/e2e/payments-stripe-connected.spec.ts
- specs/fixtures/CheckoutPage.ts
- specs/fixtures/tokenizedPage.ts
Closes #530 
This PR will change reporter to line on CI and a test for stripe connected account.
> Add connected account test and improve test output

- .vscode/settings.json
- specs/e2e/checkout.spec.ts
- specs/fixtures/CheckoutPage.ts
Closes #532 
This PR will improve the payment method selection on stripe dropin without adding timeouts.
> Improve stripe method selection on test suite

- package.json
- pnpm-lock.yaml
- specs/e2e/payments-checkoutcom.spec.ts
Closes #551 
This PR will allow to run a successful checkout with checkout.com as payment method with auto capture.
> Allow checkout.com with and without auto capture
